const mongoose=require('mongoose')
const bookSchema=new mongoose.Schema({
    title:{
        type:String,
        required:true,
        trim:true
    },
    desc:{
        type:String,
        required:true,
        trim:true
    },
    price:{
        type:Number,
        required:true
    },
    author:{
        type:String,
        required:true
    },
    category:{
        type:String,
        required:true
    },
    rentCost:{
        type:Number,
        required:true
    },
    isAvailable:{
        type:Boolean,
        default:true
    },
    numberOfCopy:{
        type:Number,
        required:true
    },
    rentedCopies:{
        type:Number,
        default:0
    },
    pages:{
        type:Number,
        required:true
    },
    isbn:{
        type:String,
        unique:true,
        default:""
    },
    image:{
        type:Object,
        default:{
            url:`https://t4.ftcdn.net/jpg/04/99/93/31/360_F_499933117_ZAUBfv3P1HEOsZDrnkbNCt4jc3AodArl.jpg`
        }
    },
    isActive:{
        type:Boolean,
        default:true
    }
},{
    collection:'books',
    timestamps:true
})
module.exports=mongoose.model("Book",bookSchema)